# Generated by Django 5.0.7 on 2024-07-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_food',
            new_name='Orderfood',
        ),
    ]
